### ISSUE TITLE
Bug: 4.1.20 LSP requests never return on large Next.js workspaces; Node server pegs 100% CPU and Reload Window leaves the original server stuck

### ISSUE THREAD

**Issue by yongsk0066** [omenien/omena-css#27]
**Extension version:** 4.1.20
**Environment:** macOS arm64, VS Code, Node 22
**Workspace:** Next.js 14 production project (~95 `.scss` files, ~hundreds of `.ts/.tsx` files, 4 internal `@design-system/*` npm packages with their own type and SCSS surfaces)

## Summary

After upgrading to 4.1.20 (with the new bundled tsgo binary), basic LSP responses (hover, codeLens, find-all-references) on a large production workspace **never return** — the language-server process pegs one CPU core at 100% for several minutes with no result, and a `Reload Window` produces a second server instance that gets stuck in the same way, with the original process not exiting.

I have spent a few hours triaging this with a separate AI assistant. **What follows separates confirmed observations from informed guesses** — the suspected root cause is reasoned from code reading, not measured by profiling, so it may be partially wrong. Hopefully the observations are still useful as a starting point.

### 1. Two server.js processes coexist after a single Reload Window, both at ~100% CPU

```
$ ps aux | grep "css-module-explainer-4.1.20"
USER  99879  100.2  1.0  ...  4:08.48  .../4.1.20/dist/server/server.js --node-ipc --clientProcessId=99865
USER   1878  104.5  0.7  ...  0:08.85  .../4.1.20/dist/server/server.js --node-ipc --clientProcessId=1864
```

PID 99879 was the original server, PID 1878 is the post-`Reload Window` instance. The original process did not exit despite the new client process taking over. Both pegged ~100% CPU simultaneously (combined ~200% on the macOS CPU column).

### 2. The Rust daemon (`engine-shadow-runner`) is not present

```
$ ps aux | grep -E "engine-shadow-runner" | grep -v grep
(empty)
```

This was the case both before and after my hover attempts. I have not been able to confirm whether this is "lazy spawn never triggered because the LSP request is stuck upstream" or "spawn failed silently."

### 3. Bundled tsgo works correctly when called directly

```
$ /Users/.../4.1.20/dist/bin/darwin-arm64/tsgo --version
Version 7.0.0-dev.20260421.2

$ /Users/.../4.1.20/dist/bin/darwin-arm64/tsgo -p ./tsconfig.json --pretty false --noEmit
shared/swr/types.ts(27,5): error TS2300: Duplicate identifier '...'.   ← real type error in my code
```

So the binary itself executes and produces output. The `tsgo probe failed for workspace` error before this report was caused by type errors in my workspace producing a non-zero exit status, which `defaultRunProbeCommand` treats as a probe failure (`tsgo-probe-type-resolver.ts:88-102`). After fixing the type errors, the probe succeeds and the failure log goes away — but the LSP responses still don't return.

### 4. Code-level facts I could read

- `tsgo-probe-type-resolver.ts:48-57`:
  ```ts
  resolve(filePath, variableName, workspaceRoot, range, options) {
      this.ensureWorkspaceProbe(workspaceRoot);              // 1× spawn per workspace, cached
      return this.fallbackResolver.resolve(...);              // ← actual work
  }
  ```
- The `fallbackResolver` defaults to `WorkspaceTypeResolver` (`tsgo-probe-type-resolver.ts:52-54`).
- `WorkspaceTypeResolver.resolve` (`type-resolver.ts:74-112`) calls `getOrCreateProgram(workspaceRoot)` then `program.getTypeChecker()` and `checker.getTypeOfSymbolAtLocation(...)`.
- `WorkspaceTypeResolver.getOrCreateProgram` (`type-resolver.ts:122-128`) caches one program per workspace, but the first build calls `createDefaultProgram(workspaceRoot)`.
- `default-program.ts:26-30`:
  ```ts
  return ts.createProgram({
      rootNames: parsed.fileNames,
      options: parsed.options,
      projectReferences: parsed.projectReferences ?? [],
  });
  ```
  i.e. a full TypeScript program is built from `tsconfig.json`'s `include` glob, with no `partialSemantic` mode and no cancellation token.

So at minimum, **every fresh CME server, on the first `resolve()` call, builds a full ts.Program of the entire workspace** before any hover/codeLens/references can return.

## Suspected root cause (informed reasoning, not measured)

I think the LSP responses don't return because **the first `WorkspaceTypeResolver.resolve()` call after server start gets stuck inside the full `ts.createProgram` build / first `getTypeChecker()` invocation on a large Next.js workspace**, and:

1. **The build is on the LSP main thread, with no cancellation.** If it takes minutes (plausible for a Next.js 14 app + 4 internal type packages + `node_modules/@types/*`), every other LSP request behind it (hover, codeLens, references) is starved on the same Node event loop, which exactly matches my symptoms ("everything is loading, nothing returns").

2. **VS Code's built-in tsserver is already doing this work in a separate process.** `ps` shows `tsserver --serverMode partialSemantic` and full `tsserver.js` running for the same workspace. CME's `WorkspaceTypeResolver` builds its own independent `ts.Program`, so the same workspace is type-checked twice from cold cache.

3. **The Rust daemon path doesn't help here**, because even though 4.1.6+ moved a lot of semantic work to Rust (`omena-semantic`, `omena-abstract-value`, etc.), the *type fact extraction* (resolving `cx`-argument variable values to TS unions, walking property chains) still runs through `WorkspaceTypeResolver.resolve` on the Node side. The bundled tsgo introduced in 4.1.20 only acts as a probe gate; it does not replace `WorkspaceTypeResolver` for actual type-fact extraction. So users on 4.1.20 still pay the full Node-side ts-program cost on first resolve, even though the changelog narrative reads as "tsgo is the default backend now."

4. **The Reload Window doesn't shut the old server down**, because the old server's main thread is busy inside `ts.createProgram` and never returns to its IPC loop to handle the LSP `shutdown` request. So the "two stuck servers at 100% CPU after one reload" pattern is consistent with this.

I cannot rule out other contributors:
- Next.js / `@next/typescript-plugin` doing additional work
- `partialSemantic` mode being insufficient if CME really does need full type info
- The daemon spawn point being upstream of `resolve()`, so daemon never gets a chance to spawn either
- Some interaction with `useInferredProjectPerProjectRoot` in vscode's tsserver

## What I'd love confirmed or corrected

1. Is `WorkspaceTypeResolver.getOrCreateProgram` indeed expected to do a *full* `ts.createProgram` on first resolve in production workspaces today, or is there a cache / partial-mode path I'm missing?
2. Is the post-4.0.0 `tsgo` default supposed to currently extract type facts itself (and `WorkspaceTypeResolver` is the legacy path), or is `tsgo` *intentionally* probe-only at the moment with full type extraction still planned to migrate?
3. Is the missing `engine-shadow-runner` process in `ps` consistent with "lazy spawn happens later in the request pipeline" or is something blocking spawn?
4. Is there a known cancellation-token plumbing path through the long resolve so that LSP `shutdown` can interrupt a stuck `ts.createProgram`?

## Suggested fix directions (ranked by suspected impact)

1. **`partialSemantic` mode (or `LanguageService` instead of `Program`)** for `WorkspaceTypeResolver`. vscode's bundled tsserver runs in `partialSemantic` for editor responsiveness; CME could do the same and only escalate to full mode when an explicit type query (like a property chain walk) actually needs it. This is the single change that I expect would change "minutes" to "seconds" on a large workspace.
2. **Background program build with cooperative yield.** Build the program off the request path; let early `resolve()` calls return `UNRESOLVABLE` or a stub until the program is warm; refresh once warm. Today the first hover blocks indefinitely.
3. **Cancellation token plumbing** on `resolve()` and `getOrCreateProgram`, wired to the LSP request token. So when vscode cancels a hover (e.g. cursor moved), the underlying program work can stop, and `shutdown` can drop a stuck server.
4. **Single-flight guard for double servers.** If a previous CME server for the same `clientProcessId` is alive and stuck, the new server should signal it and refuse to start until the predecessor exits, instead of running concurrent program builds.
5. **Long-term: move type-fact extraction to tsgo proper** so that the bundled native binary actually does the work instead of being a probe gate. This is what the 4.0.0 default change implied, but the current code shape ([`tsgo-probe-type-resolver.ts:48-57`](#)) shows tsgo is only used to validate workspace-readiness and the actual symbol resolution still goes through `WorkspaceTypeResolver`.

## Reproduction

1. Open a large Next.js 14 workspace with several thousand TypeScript source files and a few internal `@scope/*` packages contributing additional types/styles.
2. Have CME 4.1.20 installed and let it activate.
3. Hover any `$variable` or class name on a `.module.scss` file (or any `cx(...)` call site).
4. Observe: hover spinner stays indefinitely; `ps aux | grep css-module-explainer` shows the server at ~100% CPU; `ps aux | grep engine-shadow-runner` is empty.
5. `Reload Window`. Observe: a second server.js instance starts at ~100% CPU; the original is still running.

This is reproducible with no special configuration — `cssModuleExplainer.typeFactBackend` left at default `"tsgo"`, no `CME_*` environment variables set.

## Severity

This makes 4.1.20 effectively unusable on the workspace where it is most useful (large projects with cross-file design tokens). All the work in 4.1.13–4.1.19 (cross-file ranking, navigation surfaces, hover materialization) cannot be observed by the user because the response never reaches them.

I have only one workspace to test on, so it would be helpful if a reproducer in CI's `real-project-corpus` matches a similar shape (Next.js 14 + multi-package internal types) — or, if not, that's itself a useful signal that this case is uncovered.

## Closing note

Several of the layers in the suspected-root-cause section may be wrong; I'm reporting them as a starting hypothesis rather than a fix. The confirmed observations and code pointers should at least let someone with profiling access localize the actual stuck frame quickly.

**Comment by yongsk0066** [comment]
Update from 4.1.21/4.1.22 testing — your `60c7297 fix(lsp): bound sync type fact resolution` and `7d56593 fix(lsp): dispose runtimes on shutdown` are exactly the right direction (the worker-process split for type facts is what the RFC in #28 sketched as the next step). The shutdown disposal fix is also visible — no more lingering 100% CPU server after Reload Window. Thank you.

There's a packaging regression in the same release line, though. The new tsgo type-fact worker fails to spawn:

```
[Error - 5:48:02 PM] [css-module-explainer] diagnostics failed: tsgo type fact worker failed
stderr: Error: Cannot find module '/Users/.../<my-workspace>/scripts/collect-tsgo-type-facts.mjs'
    code: 'MODULE_NOT_FOUND',
```

Two issues compose:

1. **Path resolution uses `process.cwd()`**, which at LSP start equals the user's workspace, so the worker is searched under `<user-workspace>/scripts/collect-tsgo-type-facts.mjs`:

   ```ts
   // server/engine-host-node/src/tsgo-type-fact-collector.ts:155
   const workerPath = path.join(process.cwd(), "scripts/collect-tsgo-type-facts.mjs");
   ```

2. **The worker script is not bundled into the VSIX**. The installed extension layout has no `scripts/` directory at all:

   ```
   ~/.vscode/extensions/yongsk0066.css-module-explainer-4.1.21/
     ├ changelog.md
     ├ dist/
     ├ LICENSE.txt
     ├ package.json
     ├ packages/
     ├ readme.md
     └ server/
   ```

   The script exists in the source tree at `scripts/collect-tsgo-type-facts.mjs` but `rolldown.config.ts` (or the prepublish step) doesn't appear to copy it into `dist/`.

So even fixing (1) alone wouldn't help — (2) needs to ship the file alongside the runner matrix in `dist/bin/<platform>-<arch>/` or a sibling `dist/scripts/`.

Suggested fix (rough):

```ts
// (1) base on the extension dir, not cwd
const workerPath = path.join(__dirname, "..", "..", "scripts", "collect-tsgo-type-facts.mjs");
// or require.resolve from a stable anchor
```

```ts
// (2) rolldown.config.ts — add scripts/ to dist outputs
// or extend prepare-engine-shadow-runner-style step to copy worker script
```

User-visible effect: every diagnostic / hover request that goes through the new worker path emits this error and falls back through the old code path with the same `tsgo probe failed` symptom. So 4.1.21+ users on workspaces without the literal file will not benefit from the perf fix at all until packaging is corrected.

Filing as a comment here rather than a new issue since this is a direct continuation of the fix you're already shipping for this issue. Happy to open a separate one if you'd prefer.

**Comment by yongsk0066** [comment]
Followup observation from 4.1.24 testing.

The packaging regression from my previous comment is fixed (`Cannot find module ... collect-tsgo-type-facts.mjs` is gone). Thank you.

The deeper symptom on the same large workspace is unchanged:

```
$ ps aux | grep css-module-explainer | grep -v grep
PID 27494   98.0% CPU   384 MB RES   ← server.js #1
PID 20545   89.8% CPU   659 MB RES   ← server.js #2
PID 27884    0.0% CPU    15 MB RES   ← engine-shadow-runner --daemon (idle)
```

So both Node servers are still pinned at ~95% CPU each, while the Rust daemon sits idle. Two server.js instances coexisting after Reload Window also still happens.

A new symptom I hadn't noticed before: this affects unrelated VS Code features too, not just CME's own LSP. With CME 4.1.24 active on this workspace:

- VS Code built-in TypeScript "Go to References" / "Find All References" on plain React components becomes very slow.
- Hover on regular React props (no SCSS / no `cx`) also lags.
- Other extensions (e.g. ESLint inline diagnostics) feel sluggish.
- Disabling CME on this workspace immediately restores normal responsiveness.

System state at the time:

```
14 physical cores
48 GB RAM
Free pages: ~228 MB  ← memory pressure, near swap territory
```

So the cost compounds: CME's two server.js instances + VS Code's two tsserver processes + everything else. On smaller workspaces the same install is fine; on this Next.js 14 codebase (~hundreds of `.ts/.tsx`, multiple internal packages) it pegs the system.

I take this to mean the worker / cache layer fixes in 4.1.23–4.1.24 stabilized the path correctly (no more crashes / `MODULE_NOT_FOUND`), but the underlying main-thread cost on the LSP server side (large `ts.createProgram` build, no cancellation token, possibly compounded by the second server starting before the first one exits) is still unaddressed. Not sure whether that's already on your queue under #27 or whether you'd like me to file it as a separate issue specifically about "system-level CPU/memory pressure on large workspaces."

Just reporting symptoms — happy to wait for whichever direction you take next.

**Comment by yongsk0066** [comment]
I am going to keep this under #27 rather than split it for now.

The 4.1.24 follow-up and the additional local observation that hover/loading blocks other editor behavior point to the same root class of problem: CME still has expensive work that can run on or effectively serialize the LSP request path. When that happens, the Node server cannot answer hover/definition/references quickly, and the system impact compounds with VS Code's own tsserver/ESLint processes.

The packaging/worker fixes were necessary, but they are not the endpoint. The next work is to remove the architectural condition that allows a first hover or diagnostics pass to become workspace-sized blocking work.

I am aligning the fix with #28 in phases:

1. Establish a Rust `omena-lsp-server` boundary and parity gate for the current Node LSP surface.
2. Move LSP lifecycle/runtime ownership toward Rust without flipping behavior yet.
3. Move style-side providers first.
4. Replace the source-side Node `WorkspaceTypeResolver` hot path with a long-lived tsgo-backed path before source providers move fully.

The immediate success criterion for this issue is not just "no crash" or "worker path exists". It is: hover and related requests must fail fast, return stale/partial/unresolvable data, or defer background work instead of monopolizing the LSP server and degrading the rest of the editor.

**Comment by yongsk0066** [comment]
Released 4.1.25 with the #27 large-workspace request-path fixes.

What changed in this release:

- The source-side tsgo path no longer falls back into the synchronous workspace TypeScript resolver when it cannot answer immediately. Hover/definition/references/diagnostics/completion now prefer unresolved/empty fast results over rebuilding large workspace programs on the Node request path.
- The Rust LSP lane now handles already-cancelled requests before provider work starts.
- Workspace style indexing on the Rust LSP side is bounded so startup/index refresh cannot grow into unbounded request-path work.
- The packaged extension was verified with `rust-selected-query daemon=on lsp=omena-lsp-server`.

Release validation completed before publishing:

- `pnpm check`
- `pnpm test` -> 143 files / 1211 tests passed
- `pnpm build`
- packaged runner matrix check
- packaged tsgo binary check
- packaged selected-query default check
- `pnpm cme-check run rust/phase-2-swap-readiness`

I am closing #27 because the immediate failure class is now addressed: current-product requests should no longer monopolize the Node LSP server with workspace-sized synchronous work. The larger architectural destination from #28 remains open and continues as the next track: `omena-tsgo-client`, thin client endpoint, split `omena-lsp-server`, multi-editor packaging, and incremental/flow analysis.

**Comment by yongsk0066** [comment]
Post-close follow-up after 4.1.27.

- Released v4.1.27 with the Rust LSP classnames/bind source-definition parity fix found by extension-host smoke.
- Published omena-lsp-server@0.1.1 with the same Rust LSP fix in the split crate.
- The first v4.1.27 push CI failure was a CI artifact-mode issue: actions/download-artifact restored native binaries without executable bits, so extension-host could not exercise the packaged Rust LSP path correctly.
- Fixed that CI path in b84dc73 by restoring native binary permissions after build-output download and runner artifact merge.
- The follow-up CI extension-host smoke on b84dc73 is green, which confirms the original 4.1.27 product fix and separates it from the artifact permission false negative.

Leaving #27 closed. The larger no-Node-hot-path architecture remains tracked in #28.
